name: CI/CD Pipeline for Spring Boot

on:
  push:
    branches:
      - master  # Runs on push to the main branch
  pull_request:
    branches:
      - master  # Runs on pull request to main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'master'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
    
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # or the specific version you want
          distribution: 'temurin'  # or 'zulu' or 'oracle'
    
      - name: Build JAR with Maven
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build Docker image
        run: |
          docker build -t fabdev999/testci_cd:latest .


      - name: Push Docker image to Docker Hub
        run: |
          docker push fabdev999/testci_cd:latest
